name: CI

on: [push, workflow_dispatch]

jobs:

  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      # - run: npx -p wabt wat2wasm foo.wat
      - run: go run main.go
